var annotated_dup =
[
    [ "Mila", "namespaceMila.html", [
      [ "Core", "namespaceMila_1_1Core.html", [
        [ "RandomGenerator", "classMila_1_1Core_1_1RandomGenerator.html", "classMila_1_1Core_1_1RandomGenerator" ]
      ] ],
      [ "Dnn", "namespaceMila_1_1Dnn.html", [
        [ "Compute", "namespaceMila_1_1Dnn_1_1Compute.html", [
          [ "Detail", "namespaceMila_1_1Dnn_1_1Compute_1_1Detail.html", [
            [ "cuda_encoder_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__encoder__impl.html", null ],
            [ "cuda_encoder_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__encoder__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__encoder__impl_3_01float_01_4" ],
            [ "cuda_encoder_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__encoder__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__encoder__impl_3_01half_01_4" ],
            [ "cuda_gelu_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__gelu__impl.html", null ],
            [ "cuda_gelu_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__gelu__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__gelu__impl_3_01float_01_4" ],
            [ "cuda_gelu_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__gelu__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__gelu__impl_3_01half_01_4" ],
            [ "cuda_layernorm_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__layernorm__impl.html", null ],
            [ "cuda_layernorm_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__layernorm__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__layernorm__impl_3_01float_01_4" ],
            [ "cuda_layernorm_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__layernorm__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__layernorm__impl_3_01half_01_4" ],
            [ "cuda_matmul_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__matmul__impl.html", null ],
            [ "cuda_matmul_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__matmul__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__matmul__impl_3_01float_01_4" ],
            [ "cuda_matmul_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__matmul__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__matmul__impl_3_01half_01_4" ],
            [ "cuda_mha_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__mha__impl.html", null ],
            [ "cuda_mha_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__mha__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__mha__impl_3_01float_01_4" ],
            [ "cuda_mha_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__mha__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__mha__impl_3_01half_01_4" ],
            [ "cuda_residual_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__residual__impl.html", null ],
            [ "cuda_residual_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__residual__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__residual__impl_3_01float_01_4" ],
            [ "cuda_residual_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__residual__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__residual__impl_3_01half_01_4" ],
            [ "cuda_softmax_crossentropy_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__crossentropy__impl.html", null ],
            [ "cuda_softmax_crossentropy_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__crossentropy__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__crossentropy__impl_3_01float_01_4" ],
            [ "cuda_softmax_crossentropy_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__crossentropy__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__crossentropy__impl_3_01half_01_4" ],
            [ "cuda_softmax_impl", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__impl.html", null ],
            [ "cuda_softmax_impl< float >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__impl_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__impl_3_01float_01_4" ],
            [ "cuda_softmax_impl< half >", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__impl_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1Detail_1_1cuda__softmax__impl_3_01half_01_4" ]
          ] ],
          [ "AMPConfig", "classMila_1_1Dnn_1_1Compute_1_1AMPConfig.html", "classMila_1_1Dnn_1_1Compute_1_1AMPConfig" ],
          [ "BinaryOperation", "classMila_1_1Dnn_1_1Compute_1_1BinaryOperation.html", "classMila_1_1Dnn_1_1Compute_1_1BinaryOperation" ],
          [ "ComputeDevice", "classMila_1_1Dnn_1_1Compute_1_1ComputeDevice.html", "classMila_1_1Dnn_1_1Compute_1_1ComputeDevice" ],
          [ "ComputePrecision", "classMila_1_1Dnn_1_1Compute_1_1ComputePrecision.html", "classMila_1_1Dnn_1_1Compute_1_1ComputePrecision" ],
          [ "ComputeResource", "classMila_1_1Dnn_1_1Compute_1_1ComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1ComputeResource" ],
          [ "CpuCrossEntropyOp", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOp" ],
          [ "CpuCrossEntropyOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOpRegistrar" ],
          [ "CpuDevice", "classMila_1_1Dnn_1_1Compute_1_1CpuDevice.html", "classMila_1_1Dnn_1_1Compute_1_1CpuDevice" ],
          [ "CpuEncoderOp", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOp" ],
          [ "CpuEncoderOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOpRegistrar" ],
          [ "CpuGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOp" ],
          [ "CpuGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOpRegistrar" ],
          [ "CpuLayerNormOp", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOp" ],
          [ "CpuLayerNormOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOpRegistrar" ],
          [ "CpuLinearOp", "classMila_1_1Dnn_1_1Compute_1_1CpuLinearOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLinearOp" ],
          [ "CpuLinearOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuLinearOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLinearOpRegistrar" ],
          [ "CpuMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1CpuMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1CpuMemoryResource" ],
          [ "CpuMultiHeadAttentionOp", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOp" ],
          [ "CpuMultiHeadAttentionOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOpRegistrar" ],
          [ "CpuResidualOp", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOp" ],
          [ "CpuResidualOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOpRegistrar" ],
          [ "CpuSoftmaxOp", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOp" ],
          [ "CpuSoftmaxOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOpRegistrar" ],
          [ "CublasLtError", "classMila_1_1Dnn_1_1Compute_1_1CublasLtError.html", "classMila_1_1Dnn_1_1Compute_1_1CublasLtError" ],
          [ "CudaBadAlloc", "classMila_1_1Dnn_1_1Compute_1_1CudaBadAlloc.html", "classMila_1_1Dnn_1_1Compute_1_1CudaBadAlloc" ],
          [ "CudaComputeResource", "classMila_1_1Dnn_1_1Compute_1_1CudaComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1CudaComputeResource" ],
          [ "CudaDataTypeMap", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap.html", null ],
          [ "CudaDataTypeMap< __nv_bfloat16 >", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01____nv__bfloat16_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01____nv__bfloat16_01_4" ],
          [ "CudaDataTypeMap< float >", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01float_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01float_01_4" ],
          [ "CudaDataTypeMap< half >", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01half_01_4.html", "structMila_1_1Dnn_1_1Compute_1_1CudaDataTypeMap_3_01half_01_4" ],
          [ "CudaDevice", "classMila_1_1Dnn_1_1Compute_1_1CudaDevice.html", "classMila_1_1Dnn_1_1Compute_1_1CudaDevice" ],
          [ "CudaEncoderOp", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOp" ],
          [ "CudaEncoderOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOpRegistrar" ],
          [ "CudaError", "classMila_1_1Dnn_1_1Compute_1_1CudaError.html", "classMila_1_1Dnn_1_1Compute_1_1CudaError" ],
          [ "CudaGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOp" ],
          [ "CudaGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOpRegistrar" ],
          [ "CudaLayerNormOp", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOp" ],
          [ "CudaLayerNormOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOpRegistrar" ],
          [ "CudaLinearOp", "classMila_1_1Dnn_1_1Compute_1_1CudaLinearOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLinearOp" ],
          [ "CudaLinearOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaLinearOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLinearOpRegistrar" ],
          [ "CudaManagedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1CudaManagedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1CudaManagedMemoryResource" ],
          [ "CudaMatMulBiasGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOp" ],
          [ "CudaMatMulBiasGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOpRegistrar" ],
          [ "CudaMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1CudaMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMemoryResource" ],
          [ "CudaMultiHeadAttentionOp", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOp" ],
          [ "CudaMultiHeadAttentionOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOpRegistrar" ],
          [ "CudaPinnedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1CudaPinnedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1CudaPinnedMemoryResource" ],
          [ "CudaResidualOp", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOp" ],
          [ "CudaResidualOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOpRegistrar" ],
          [ "CudaSoftmaxOp", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOp" ],
          [ "CudaSoftmaxOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOpRegistrar" ],
          [ "DeviceAccessible", "structMila_1_1Dnn_1_1Compute_1_1DeviceAccessible.html", "structMila_1_1Dnn_1_1Compute_1_1DeviceAccessible" ],
          [ "DeviceContext", "classMila_1_1Dnn_1_1Compute_1_1DeviceContext.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceContext" ],
          [ "DeviceProps", "classMila_1_1Dnn_1_1Compute_1_1DeviceProps.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceProps" ],
          [ "DeviceRegistrar", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistrar" ],
          [ "DeviceRegistry", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistry.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistry" ],
          [ "DynamicMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1DynamicMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1DynamicMemoryResource" ],
          [ "FusedOpMeta", "structMila_1_1Dnn_1_1Compute_1_1FusedOpMeta.html", "structMila_1_1Dnn_1_1Compute_1_1FusedOpMeta" ],
          [ "FusedSoftmaxCrossEntropyOp", "classMila_1_1Dnn_1_1Compute_1_1FusedSoftmaxCrossEntropyOp.html", "classMila_1_1Dnn_1_1Compute_1_1FusedSoftmaxCrossEntropyOp" ],
          [ "FusedSoftmaxCrossEntropyOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1FusedSoftmaxCrossEntropyOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1FusedSoftmaxCrossEntropyOpRegistrar" ],
          [ "HostAccessible", "structMila_1_1Dnn_1_1Compute_1_1HostAccessible.html", "structMila_1_1Dnn_1_1Compute_1_1HostAccessible" ],
          [ "HostComputeResource", "classMila_1_1Dnn_1_1Compute_1_1HostComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1HostComputeResource" ],
          [ "MemoryStats", "structMila_1_1Dnn_1_1Compute_1_1MemoryStats.html", "structMila_1_1Dnn_1_1Compute_1_1MemoryStats" ],
          [ "OperationAttributes", "structMila_1_1Dnn_1_1Compute_1_1OperationAttributes.html", "structMila_1_1Dnn_1_1Compute_1_1OperationAttributes" ],
          [ "OperationBase", "classMila_1_1Dnn_1_1Compute_1_1OperationBase.html", "classMila_1_1Dnn_1_1Compute_1_1OperationBase" ],
          [ "OperationRegistry", "classMila_1_1Dnn_1_1Compute_1_1OperationRegistry.html", "classMila_1_1Dnn_1_1Compute_1_1OperationRegistry" ],
          [ "OperationsRegistrar", "classMila_1_1Dnn_1_1Compute_1_1OperationsRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1OperationsRegistrar" ],
          [ "TrackedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1TrackedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1TrackedMemoryResource" ],
          [ "UnaryOperation", "classMila_1_1Dnn_1_1Compute_1_1UnaryOperation.html", "classMila_1_1Dnn_1_1Compute_1_1UnaryOperation" ]
        ] ],
        [ "Data", "namespaceMila_1_1Dnn_1_1Data.html", [
          [ "DataLoader", "classMila_1_1Dnn_1_1Data_1_1DataLoader.html", "classMila_1_1Dnn_1_1Data_1_1DataLoader" ]
        ] ],
        [ "Gpt2", "namespaceMila_1_1Dnn_1_1Gpt2.html", [
          [ "DatasetReader", "classMila_1_1Dnn_1_1Gpt2_1_1DatasetReader.html", "classMila_1_1Dnn_1_1Gpt2_1_1DatasetReader" ],
          [ "DSReaderConfig", "structMila_1_1Dnn_1_1Gpt2_1_1DSReaderConfig.html", "structMila_1_1Dnn_1_1Gpt2_1_1DSReaderConfig" ]
        ] ],
        [ "Serialization", "namespaceMila_1_1Dnn_1_1Serialization.html", [
          [ "ModelArchive", "classMila_1_1Dnn_1_1Serialization_1_1ModelArchive.html", "classMila_1_1Dnn_1_1Serialization_1_1ModelArchive" ],
          [ "ModelSerializer", "classMila_1_1Dnn_1_1Serialization_1_1ModelSerializer.html", "classMila_1_1Dnn_1_1Serialization_1_1ModelSerializer" ],
          [ "ZipSerializer", "classMila_1_1Dnn_1_1Serialization_1_1ZipSerializer.html", "classMila_1_1Dnn_1_1Serialization_1_1ZipSerializer" ]
        ] ],
        [ "Component", "classMila_1_1Dnn_1_1Component.html", "classMila_1_1Dnn_1_1Component" ],
        [ "ComponentConfig", "classMila_1_1Dnn_1_1ComponentConfig.html", "classMila_1_1Dnn_1_1ComponentConfig" ],
        [ "CompositeModule", "classMila_1_1Dnn_1_1CompositeModule.html", "classMila_1_1Dnn_1_1CompositeModule" ],
        [ "CrossEntropy", "classMila_1_1Dnn_1_1CrossEntropy.html", "classMila_1_1Dnn_1_1CrossEntropy" ],
        [ "CrossEntropyConfig", "classMila_1_1Dnn_1_1CrossEntropyConfig.html", "classMila_1_1Dnn_1_1CrossEntropyConfig" ],
        [ "Dropout", "classMila_1_1Dnn_1_1Dropout.html", "classMila_1_1Dnn_1_1Dropout" ],
        [ "DropoutConfig", "classMila_1_1Dnn_1_1DropoutConfig.html", "classMila_1_1Dnn_1_1DropoutConfig" ],
        [ "Encoder", "classMila_1_1Dnn_1_1Encoder.html", "classMila_1_1Dnn_1_1Encoder" ],
        [ "EncoderConfig", "classMila_1_1Dnn_1_1EncoderConfig.html", "classMila_1_1Dnn_1_1EncoderConfig" ],
        [ "FusedModule", "classMila_1_1Dnn_1_1FusedModule.html", "classMila_1_1Dnn_1_1FusedModule" ],
        [ "Gelu", "classMila_1_1Dnn_1_1Gelu.html", "classMila_1_1Dnn_1_1Gelu" ],
        [ "GeluConfig", "classMila_1_1Dnn_1_1GeluConfig.html", "classMila_1_1Dnn_1_1GeluConfig" ],
        [ "LayerNorm", "classMila_1_1Dnn_1_1LayerNorm.html", "classMila_1_1Dnn_1_1LayerNorm" ],
        [ "LayerNormConfig", "classMila_1_1Dnn_1_1LayerNormConfig.html", "classMila_1_1Dnn_1_1LayerNormConfig" ],
        [ "Linear", "classMila_1_1Dnn_1_1Linear.html", "classMila_1_1Dnn_1_1Linear" ],
        [ "LinearConfig", "classMila_1_1Dnn_1_1LinearConfig.html", "classMila_1_1Dnn_1_1LinearConfig" ],
        [ "MLP", "classMila_1_1Dnn_1_1MLP.html", "classMila_1_1Dnn_1_1MLP" ],
        [ "MLPConfig", "classMila_1_1Dnn_1_1MLPConfig.html", "classMila_1_1Dnn_1_1MLPConfig" ],
        [ "Model", "classMila_1_1Dnn_1_1Model.html", "classMila_1_1Dnn_1_1Model" ],
        [ "ModelCallback", "classMila_1_1Dnn_1_1ModelCallback.html", "classMila_1_1Dnn_1_1ModelCallback" ],
        [ "Module", "classMila_1_1Dnn_1_1Module.html", "classMila_1_1Dnn_1_1Module" ],
        [ "MultiHeadAttention", "classMila_1_1Dnn_1_1MultiHeadAttention.html", "classMila_1_1Dnn_1_1MultiHeadAttention" ],
        [ "MultiHeadAttentionConfig", "classMila_1_1Dnn_1_1MultiHeadAttentionConfig.html", "classMila_1_1Dnn_1_1MultiHeadAttentionConfig" ],
        [ "Residual", "classMila_1_1Dnn_1_1Residual.html", "classMila_1_1Dnn_1_1Residual" ],
        [ "ResidualConfig", "classMila_1_1Dnn_1_1ResidualConfig.html", "classMila_1_1Dnn_1_1ResidualConfig" ],
        [ "Softmax", "classMila_1_1Dnn_1_1Softmax.html", "classMila_1_1Dnn_1_1Softmax" ],
        [ "SoftmaxConfig", "classMila_1_1Dnn_1_1SoftmaxConfig.html", "classMila_1_1Dnn_1_1SoftmaxConfig" ],
        [ "Tensor", "classMila_1_1Dnn_1_1Tensor.html", "classMila_1_1Dnn_1_1Tensor" ],
        [ "TensorBuffer", "classMila_1_1Dnn_1_1TensorBuffer.html", "classMila_1_1Dnn_1_1TensorBuffer" ],
        [ "TensorPtr", "classMila_1_1Dnn_1_1TensorPtr.html", "classMila_1_1Dnn_1_1TensorPtr" ],
        [ "TensorTrait", "structMila_1_1Dnn_1_1TensorTrait.html", null ],
        [ "TensorTrait< __nv_fp8_e4m3 >", "structMila_1_1Dnn_1_1TensorTrait_3_01____nv__fp8__e4m3_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01____nv__fp8__e4m3_01_4" ],
        [ "TensorTrait< __nv_fp8_e5m2 >", "structMila_1_1Dnn_1_1TensorTrait_3_01____nv__fp8__e5m2_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01____nv__fp8__e5m2_01_4" ],
        [ "TensorTrait< float >", "structMila_1_1Dnn_1_1TensorTrait_3_01float_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01float_01_4" ],
        [ "TensorTrait< half >", "structMila_1_1Dnn_1_1TensorTrait_3_01half_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01half_01_4" ],
        [ "TensorTrait< int >", "structMila_1_1Dnn_1_1TensorTrait_3_01int_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01int_01_4" ],
        [ "TensorTrait< int16_t >", "structMila_1_1Dnn_1_1TensorTrait_3_01int16__t_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01int16__t_01_4" ],
        [ "TensorTrait< nv_bfloat16 >", "structMila_1_1Dnn_1_1TensorTrait_3_01nv__bfloat16_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01nv__bfloat16_01_4" ],
        [ "TensorTrait< uint16_t >", "structMila_1_1Dnn_1_1TensorTrait_3_01uint16__t_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01uint16__t_01_4" ],
        [ "TensorTrait< uint32_t >", "structMila_1_1Dnn_1_1TensorTrait_3_01uint32__t_01_4.html", "structMila_1_1Dnn_1_1TensorTrait_3_01uint32__t_01_4" ],
        [ "TrainingConfig", "structMila_1_1Dnn_1_1TrainingConfig.html", "structMila_1_1Dnn_1_1TrainingConfig" ],
        [ "TransformerBlock", "classMila_1_1Dnn_1_1TransformerBlock.html", "classMila_1_1Dnn_1_1TransformerBlock" ],
        [ "TransformerBlockConfig", "classMila_1_1Dnn_1_1TransformerBlockConfig.html", "classMila_1_1Dnn_1_1TransformerBlockConfig" ],
        [ "UniqueIdGenerator", "classMila_1_1Dnn_1_1UniqueIdGenerator.html", "classMila_1_1Dnn_1_1UniqueIdGenerator" ]
      ] ],
      [ "Misc", "namespaceMila_1_1Misc.html", [
        [ "glob_t", "structMila_1_1Misc_1_1glob__t.html", "structMila_1_1Misc_1_1glob__t" ]
      ] ],
      [ "Utils", "namespaceMila_1_1Utils.html", [
        [ "DefaultLogger", "classMila_1_1Utils_1_1DefaultLogger.html", "classMila_1_1Utils_1_1DefaultLogger" ],
        [ "Logger", "classMila_1_1Utils_1_1Logger.html", "classMila_1_1Utils_1_1Logger" ],
        [ "StepLogger", "classMila_1_1Utils_1_1StepLogger.html", "classMila_1_1Utils_1_1StepLogger" ]
      ] ],
      [ "Version", "structMila_1_1Version.html", "structMila_1_1Version" ]
    ] ],
    [ "Config", "structConfig.html", null ],
    [ "CudaException", "classCudaException.html", "classCudaException" ]
];