"""
Marks the distribution as binary, and supplies the version.

Everything else is declarative in pyproject.toml. This file exists for two reasons:

The compiled extension is staged into src/mila by the CMake build rather than built by
setuptools, so setuptools sees no ext_modules and would tag the result py3-none-any -- a
pure-Python wheel that pip would happily install under the wrong interpreter and
platform, where the extension cannot load. Declaring has_ext_modules() forces the real
cp3XX-cp3XX-<platform> tag.

And the version is derived from the repository's Version.txt by the CMake build (see
cmake/MilaVersion.cmake) into the generated VERSION file beside this one, rather than
hand-copied into pyproject.toml -- where it silently drifted 18 builds behind. A missing
VERSION means this package tree was never built, which is an error rather than a default:
guessing here would publish a wrong number, and a published version can never be reused.
"""

from pathlib import Path

from setuptools import setup
from setuptools.dist import Distribution


class BinaryDistribution(Distribution):
    def has_ext_modules(self) -> bool:
        return True


def read_version() -> str:
    version_file = Path(__file__).parent / "VERSION"

    if not version_file.is_file():
        raise SystemExit(
            f"{version_file} is missing. It is generated by the CMake build, which "
            "derives it from Version.txt -- build the MilaPy target before packaging."
        )

    return version_file.read_text(encoding="utf-8").strip()


setup(distclass=BinaryDistribution, version=read_version())
