services:
  mila-dev:
    extends:
      file: docker-compose.yml
      service: mila-dev
    volumes:
      - ..:/mila
      - build-cache:/mila/build
    environment:
      - CMAKE_BUILD_TYPE=Debug
      - MILA_ENABLE_TESTING=ON

volumes:
  build-cache: