var annotated_dup =
[
    [ "Mila", "namespaceMila.html", [
      [ "Data", "namespaceMila_1_1Data.html", [
        [ "DataLoader", "classMila_1_1Data_1_1DataLoader.html", "classMila_1_1Data_1_1DataLoader" ]
      ] ],
      [ "Dnn", "namespaceMila_1_1Dnn.html", [
        [ "Compute", "namespaceMila_1_1Dnn_1_1Compute.html", [
          [ "BinaryOperation", "classMila_1_1Dnn_1_1Compute_1_1BinaryOperation.html", "classMila_1_1Dnn_1_1Compute_1_1BinaryOperation" ],
          [ "ComputeDevice", "classMila_1_1Dnn_1_1Compute_1_1ComputeDevice.html", "classMila_1_1Dnn_1_1Compute_1_1ComputeDevice" ],
          [ "ComputeResource", "classMila_1_1Dnn_1_1Compute_1_1ComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1ComputeResource" ],
          [ "CpuCrossEntropyOp", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOp" ],
          [ "CpuCrossEntropyOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuCrossEntropyOpRegistrar" ],
          [ "CpuDevice", "classMila_1_1Dnn_1_1Compute_1_1CpuDevice.html", "classMila_1_1Dnn_1_1Compute_1_1CpuDevice" ],
          [ "CpuEncoderOp", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOp" ],
          [ "CpuEncoderOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuEncoderOpRegistrar" ],
          [ "CpuFullyConnectedOp", "classMila_1_1Dnn_1_1Compute_1_1CpuFullyConnectedOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuFullyConnectedOp" ],
          [ "CpuFullyConnectedOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuFullyConnectedOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuFullyConnectedOpRegistrar" ],
          [ "CpuGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOp" ],
          [ "CpuGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuGeluOpRegistrar" ],
          [ "CpuLayerNormOp", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOp" ],
          [ "CpuLayerNormOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuLayerNormOpRegistrar" ],
          [ "CpuMultiHeadAttentionOp", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOp" ],
          [ "CpuMultiHeadAttentionOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuMultiHeadAttentionOpRegistrar" ],
          [ "CpuResidualOp", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOp" ],
          [ "CpuResidualOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuResidualOpRegistrar" ],
          [ "CpuSoftmaxOp", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOp.html", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOp" ],
          [ "CpuSoftmaxOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CpuSoftmaxOpRegistrar" ],
          [ "CudaBadAlloc", "classMila_1_1Dnn_1_1Compute_1_1CudaBadAlloc.html", "classMila_1_1Dnn_1_1Compute_1_1CudaBadAlloc" ],
          [ "CudaComputeResource", "classMila_1_1Dnn_1_1Compute_1_1CudaComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1CudaComputeResource" ],
          [ "CudaDevice", "classMila_1_1Dnn_1_1Compute_1_1CudaDevice.html", "classMila_1_1Dnn_1_1Compute_1_1CudaDevice" ],
          [ "CudaEncoderOp", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOp" ],
          [ "CudaEncoderOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaEncoderOpRegistrar" ],
          [ "CudaError", "classMila_1_1Dnn_1_1Compute_1_1CudaError.html", "classMila_1_1Dnn_1_1Compute_1_1CudaError" ],
          [ "CudaFullyConnectedOp", "classMila_1_1Dnn_1_1Compute_1_1CudaFullyConnectedOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaFullyConnectedOp" ],
          [ "CudaFullyConnectedOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaFullyConnectedOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaFullyConnectedOpRegistrar" ],
          [ "CudaGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOp" ],
          [ "CudaGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaGeluOpRegistrar" ],
          [ "CudaLayerNormOp", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOp" ],
          [ "CudaLayerNormOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaLayerNormOpRegistrar" ],
          [ "CudaMatMulBiasGeluOp", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOp" ],
          [ "CudaMatMulBiasGeluOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMatMulBiasGeluOpRegistrar" ],
          [ "CudaMultiHeadAttentionOp", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOp" ],
          [ "CudaMultiHeadAttentionOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaMultiHeadAttentionOpRegistrar" ],
          [ "CudaResidualOp", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOp" ],
          [ "CudaResidualOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaResidualOpRegistrar" ],
          [ "CudaSoftmaxOp", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOp.html", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOp" ],
          [ "CudaSoftmaxOpRegistrar", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOpRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1CudaSoftmaxOpRegistrar" ],
          [ "DeviceAccessible", "structMila_1_1Dnn_1_1Compute_1_1DeviceAccessible.html", "structMila_1_1Dnn_1_1Compute_1_1DeviceAccessible" ],
          [ "DeviceContext", "classMila_1_1Dnn_1_1Compute_1_1DeviceContext.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceContext" ],
          [ "DeviceMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1DeviceMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceMemoryResource" ],
          [ "DeviceProps", "classMila_1_1Dnn_1_1Compute_1_1DeviceProps.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceProps" ],
          [ "DeviceRegistrar", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistrar" ],
          [ "DeviceRegistry", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistry.html", "classMila_1_1Dnn_1_1Compute_1_1DeviceRegistry" ],
          [ "DynamicMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1DynamicMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1DynamicMemoryResource" ],
          [ "FusedOpMeta", "structMila_1_1Dnn_1_1Compute_1_1FusedOpMeta.html", "structMila_1_1Dnn_1_1Compute_1_1FusedOpMeta" ],
          [ "HostAccessible", "structMila_1_1Dnn_1_1Compute_1_1HostAccessible.html", "structMila_1_1Dnn_1_1Compute_1_1HostAccessible" ],
          [ "HostComputeResource", "classMila_1_1Dnn_1_1Compute_1_1HostComputeResource.html", "classMila_1_1Dnn_1_1Compute_1_1HostComputeResource" ],
          [ "HostMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1HostMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1HostMemoryResource" ],
          [ "ManagedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1ManagedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1ManagedMemoryResource" ],
          [ "MemoryStats", "structMila_1_1Dnn_1_1Compute_1_1MemoryStats.html", "structMila_1_1Dnn_1_1Compute_1_1MemoryStats" ],
          [ "OperationAttributes", "structMila_1_1Dnn_1_1Compute_1_1OperationAttributes.html", "structMila_1_1Dnn_1_1Compute_1_1OperationAttributes" ],
          [ "OperationBase", "classMila_1_1Dnn_1_1Compute_1_1OperationBase.html", "classMila_1_1Dnn_1_1Compute_1_1OperationBase" ],
          [ "OperationRegistry", "classMila_1_1Dnn_1_1Compute_1_1OperationRegistry.html", "classMila_1_1Dnn_1_1Compute_1_1OperationRegistry" ],
          [ "OperationsRegistrar", "classMila_1_1Dnn_1_1Compute_1_1OperationsRegistrar.html", "classMila_1_1Dnn_1_1Compute_1_1OperationsRegistrar" ],
          [ "PinnedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1PinnedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1PinnedMemoryResource" ],
          [ "TrackedMemoryResource", "classMila_1_1Dnn_1_1Compute_1_1TrackedMemoryResource.html", "classMila_1_1Dnn_1_1Compute_1_1TrackedMemoryResource" ],
          [ "UnaryOperation", "classMila_1_1Dnn_1_1Compute_1_1UnaryOperation.html", "classMila_1_1Dnn_1_1Compute_1_1UnaryOperation" ]
        ] ],
        [ "Gpt2", "namespaceMila_1_1Dnn_1_1Gpt2.html", [
          [ "DatasetReader", "classMila_1_1Dnn_1_1Gpt2_1_1DatasetReader.html", "classMila_1_1Dnn_1_1Gpt2_1_1DatasetReader" ]
        ] ],
        [ "Block", "classMila_1_1Dnn_1_1Block.html", "classMila_1_1Dnn_1_1Block" ],
        [ "Encoder", "classMila_1_1Dnn_1_1Encoder.html", "classMila_1_1Dnn_1_1Encoder" ],
        [ "FullyConnected", "classMila_1_1Dnn_1_1FullyConnected.html", "classMila_1_1Dnn_1_1FullyConnected" ],
        [ "FusedModule", "classMila_1_1Dnn_1_1FusedModule.html", "classMila_1_1Dnn_1_1FusedModule" ],
        [ "Gelu", "classMila_1_1Dnn_1_1Gelu.html", "classMila_1_1Dnn_1_1Gelu" ],
        [ "LayerNorm", "classMila_1_1Dnn_1_1LayerNorm.html", "classMila_1_1Dnn_1_1LayerNorm" ],
        [ "MLP", "classMila_1_1Dnn_1_1MLP.html", "classMila_1_1Dnn_1_1MLP" ],
        [ "Model", "classMila_1_1Dnn_1_1Model.html", "classMila_1_1Dnn_1_1Model" ],
        [ "ModelCallback", "classMila_1_1Dnn_1_1ModelCallback.html", "classMila_1_1Dnn_1_1ModelCallback" ],
        [ "Module", "classMila_1_1Dnn_1_1Module.html", "classMila_1_1Dnn_1_1Module" ],
        [ "MultiHeadAttention", "classMila_1_1Dnn_1_1MultiHeadAttention.html", "classMila_1_1Dnn_1_1MultiHeadAttention" ],
        [ "Residual", "classMila_1_1Dnn_1_1Residual.html", "classMila_1_1Dnn_1_1Residual" ],
        [ "Softmax", "classMila_1_1Dnn_1_1Softmax.html", "classMila_1_1Dnn_1_1Softmax" ],
        [ "Tensor", "classMila_1_1Dnn_1_1Tensor.html", "classMila_1_1Dnn_1_1Tensor" ],
        [ "TensorBuffer", "classMila_1_1Dnn_1_1TensorBuffer.html", "classMila_1_1Dnn_1_1TensorBuffer" ],
        [ "TensorPtr", "classMila_1_1Dnn_1_1TensorPtr.html", "classMila_1_1Dnn_1_1TensorPtr" ],
        [ "TensorTypeTrait", "structMila_1_1Dnn_1_1TensorTypeTrait.html", null ],
        [ "TensorTypeTrait< float >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01float_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01float_01_4" ],
        [ "TensorTypeTrait< half >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01half_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01half_01_4" ],
        [ "TensorTypeTrait< int >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01int_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01int_01_4" ],
        [ "TensorTypeTrait< int16_t >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01int16__t_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01int16__t_01_4" ],
        [ "TensorTypeTrait< uint16_t >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01uint16__t_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01uint16__t_01_4" ],
        [ "TensorTypeTrait< uint32_t >", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01uint32__t_01_4.html", "structMila_1_1Dnn_1_1TensorTypeTrait_3_01uint32__t_01_4" ],
        [ "TrainingConfig", "structMila_1_1Dnn_1_1TrainingConfig.html", "structMila_1_1Dnn_1_1TrainingConfig" ],
        [ "TransformerBlock", "classMila_1_1Dnn_1_1TransformerBlock.html", "classMila_1_1Dnn_1_1TransformerBlock" ],
        [ "UniqueIdGenerator", "classMila_1_1Dnn_1_1UniqueIdGenerator.html", "classMila_1_1Dnn_1_1UniqueIdGenerator" ]
      ] ],
      [ "Misc", "namespaceMila_1_1Misc.html", [
        [ "glob_t", "structMila_1_1Misc_1_1glob__t.html", "structMila_1_1Misc_1_1glob__t" ]
      ] ],
      [ "Utils", "namespaceMila_1_1Utils.html", [
        [ "DefaultLogger", "classMila_1_1Utils_1_1DefaultLogger.html", "classMila_1_1Utils_1_1DefaultLogger" ],
        [ "Logger", "classMila_1_1Utils_1_1Logger.html", "classMila_1_1Utils_1_1Logger" ],
        [ "StepLogger", "classMila_1_1Utils_1_1StepLogger.html", "classMila_1_1Utils_1_1StepLogger" ]
      ] ],
      [ "Version", "structMila_1_1Version.html", "structMila_1_1Version" ]
    ] ],
    [ "CudaException", "classCudaException.html", "classCudaException" ],
    [ "DIR", "structDIR.html", "structDIR" ],
    [ "dirent", "structdirent.html", "structdirent" ],
    [ "mt19937_state", "structmt19937__state.html", "structmt19937__state" ]
];