/**
 * @file GatedDeltaRule.Cuda.cpp
 * @brief Concrete-component tests for GatedDeltaRule<DeviceType::Cuda, {FP32, BF16}>.
 *
 * The expected values below are not hand-derived: they come from an independent Python
 * implementation of the rule that was first proven bit-identical (max |diff| = 0.0) to
 * `transformers.models.qwen3_5.torch_recurrent_gated_delta_rule` on these same inputs. So
 * a failure here means the CUDA kernel diverges from the reference implementation, not
 * from someone's reading of it.
 *
 * The generator lives in the session scratchpad as delta_rule_oracle.py, seed 20260819;
 * geometry is deliberately tiny (2 key heads, 6 value heads, head dims 4) so the vectors
 * fit in a source file and the head grouping (3 value heads per key head) is exercised.
 *
 * Compiled only under MILA_ENABLE_CUDA; SetUp() skips if no device at runtime.
 */

#include <gtest/gtest.h>
#include <cmath>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

import Mila;
import Compute.ExecutionContext;

namespace Mila::Tests::Dnn::Components::DeltaNet
{
    using namespace Mila::Dnn;
    using namespace Mila::Dnn::Compute;

    namespace
    {
        struct Fp32Precision
        {
            static constexpr TensorDataType value = TensorDataType::FP32;
            static constexpr float atol = 1e-5f;
            static constexpr const char* name = "Fp32";
        };

        struct Bf16Precision
        {
            static constexpr TensorDataType value = TensorDataType::BF16;
            // The recurrence accumulates in FP32 but q/k/v/a/b arrive BF16, so the input
            // rounding propagates through every step. Loose by design.
            static constexpr float atol = 2e-2f;
            static constexpr const char* name = "Bf16";
        };

        using DeltaRulePrecisions = ::testing::Types<Fp32Precision, Bf16Precision>;

        class PrecisionNames
        {
        public:
            template<typename TPrecisionTag>
            static std::string GetName( int )
            {
                return TPrecisionTag::name;
            }
        };

        constexpr dim_t kBatch = 1;
        constexpr dim_t kSteps = 5;
        constexpr dim_t kKeyHeads = 2;
        constexpr dim_t kValueHeads = 6;
        constexpr dim_t kHeadKeyDim = 4;
        constexpr dim_t kHeadValueDim = 4;
        constexpr dim_t kKeyWidth = kKeyHeads * kHeadKeyDim;
        constexpr dim_t kValueWidth = kValueHeads * kHeadValueDim;

        // ---- generated by delta_rule_oracle.py, seed 20260819 ----
        static constexpr float kQ[] = { 1.05705464f, 1.44421279f, -0.28207618f, 1.34406805f, -0.24894632f, -0.35209745f, 0.56162727f, 1.43236530f, 0.14786828f, 1.46781456f, -1.72898018f, 0.38752419f, -0.36124966f, -0.03852576f, 0.42569640f, -0.58954930f, -0.90253323f, -0.83942890f, -1.24193430f, -0.79828852f, 1.18322778f, -1.98333228f, 0.45120141f, -1.16295266f, 1.11489928f, 2.23451161f, -0.16044247f, -0.85984623f, -0.44878489f, -0.08352322f, 0.18415673f, -0.29725680f, -2.39690495f, -1.02603257f, -0.08978408f, -1.08331931f, -2.41726565f, -0.75296527f, 1.54356372f, -0.38646945f };

        static constexpr float kK[] = { 0.51512873f, 0.52369690f, -0.24314360f, -0.89409006f, 0.02833949f, 0.66830873f, -0.20664166f, 0.45517504f, -1.40313911f, -1.49992824f, 1.65911007f, 0.29586226f, 0.02743289f, -0.47586161f, 0.32010028f, 0.19459344f, -1.59062684f, -0.47742298f, 0.01511013f, -0.37076524f, 0.84459299f, -1.10163069f, -1.18762004f, 1.43959069f, 0.76561141f, -0.16311520f, 1.95577550f, 2.26063395f, -1.01325047f, 0.01468214f, 1.08488727f, -0.99071157f, 0.44533166f, -1.17938018f, -0.36608893f, 0.39010081f, -0.52604550f, -1.77198040f, 0.30997291f, 1.70180941f };

        static constexpr float kV[] = { -0.93039393f, 1.23692751f, -1.16809618f, 0.20896040f, -0.07304917f, 1.19814527f, -0.14460102f, 0.26151353f, -1.66809571f, -0.71040863f, -0.73731244f, 0.64460617f, 0.30209839f, -1.55141127f, -1.08423817f, 0.82472891f, 1.13151109f, -1.00455356f, -1.43640816f, -1.52544117f, 0.18873377f, 0.31342587f, 0.62671959f, 0.97521418f, 0.80179834f, 0.28575599f, 0.22024269f, -1.16358805f, -1.24520075f, 0.80424827f, -0.02859749f, -0.12638266f, -1.83920085f, 0.28713235f, 0.63904852f, -1.73722959f, 1.57390118f, -1.98116386f, 1.65092659f, -0.45082769f, 1.04877841f, 0.26407269f, 0.51059759f, -1.94094002f, 1.63868940f, -0.15680431f, -1.03621089f, -0.84076917f, -0.67262393f, 0.45321041f, -0.14218473f, 0.52326626f, 0.42681995f, -0.76767612f, 0.30088511f, 0.62166840f, -0.85034794f, 1.19379771f, -0.31669697f, 0.02975057f, 1.48981619f, 0.79153877f, 0.27950165f, 0.71432036f, -0.39862317f, -1.61327684f, 0.09710249f, -1.66975486f, -1.17259824f, -1.06897247f, 1.15270126f, 0.05398748f, 0.04653400f, 0.21682912f, 0.54264069f, 0.37949678f, -1.10723448f, -0.47537854f, -0.14109719f, 0.97900337f, -0.03496336f, 0.64319092f, -0.81796724f, -0.36260056f, 0.80267429f, -1.11809242f, -0.49641821f, 0.28194425f, -0.98838836f, -2.18700051f, 0.48741943f, -0.93060321f, 0.46738577f, -0.00165446f, -0.50867623f, -0.34414527f, -1.60398948f, 1.76005507f, -0.66321051f, 1.68116021f, -0.63446242f, -1.14930725f, -0.61889094f, -0.13165191f, -0.66749513f, -0.46859357f, -1.13658631f, 1.39645147f, -0.87644088f, -2.75275087f, -1.71047997f, -0.17475589f, 0.92975849f, 0.34466249f, -0.50480819f, 0.68516016f, -1.05087674f, -0.13240187f, 0.79990798f, 0.17338556f };

        static constexpr float kA[] = { -0.13974093f, -1.46453726f, 0.41820452f, 0.38623208f, -0.00425688f, 0.49934173f, -1.00336421f, 2.20248270f, 0.38398138f, 0.12577532f, -0.59895486f, 1.99951172f, -0.42756030f, 0.95718545f, 0.33197996f, 0.86469173f, 1.85532188f, 1.02893162f, -0.49810359f, -0.48944792f, -2.10644603f, 0.42673030f, -0.99422312f, 0.54020089f, -1.20903742f, -2.66140461f, -1.59693897f, 0.29994959f, -1.18506372f, 0.89684218f };

        static constexpr float kB[] = { 0.26933718f, -1.72954690f, -0.29514074f, 0.34280843f, 0.54095882f, 0.50893855f, 1.81579924f, 2.70643544f, 0.93539447f, 0.88824219f, 0.20952514f, 0.37571675f, -0.11815063f, -0.70197475f, 0.08987319f, 0.78100348f, 0.04038204f, 1.16408288f, -1.51714659f, -0.02998285f, 0.92341101f, -0.37990007f, 0.22534779f, -0.18120773f, -2.19400597f, 0.40527984f, 1.39167345f, 0.73923546f, -0.96731287f, -0.55279768f };

        static constexpr float kALog[] = { -0.00810267f, -0.98629463f, 0.57363623f, 0.11149225f, -0.01736570f, 0.04299238f };

        static constexpr float kDtBias[] = { -1.18187070f, -0.38994655f, 0.58872199f, 1.44299650f, -0.82737941f, 0.43788269f };

        static constexpr float kExpectedOut[] = { -0.01658218f, 0.02204548f, -0.02081873f, 0.00372425f, -0.00034595f, 0.00567428f, -0.00068481f, 0.00123850f, -0.02237873f, -0.00953065f, -0.00989160f, 0.00864786f, 0.01943678f, -0.09981665f, -0.06975909f, 0.05306245f, 0.07867107f, -0.06984404f, -0.09986977f, -0.10606000f, 0.01296692f, 0.02153387f, 0.04305867f, 0.06700194f, -0.25142542f, -0.15567133f, -0.03062780f, 0.41294301f, 0.49246821f, -0.32684016f, 0.01239859f, 0.04793534f, 0.55959272f, -0.08564518f, -0.19210652f, 0.52463973f, 0.02706173f, -0.00753614f, 0.06012353f, -0.02839296f, -0.14398366f, 0.14789380f, 0.21370581f, 0.18526268f, 0.02717519f, -0.00674780f, -0.02651848f, -0.02735599f, -0.15911558f, 0.07290203f, -0.05139699f, 0.14440402f, 0.08180445f, -0.10351754f, 0.03278137f, 0.07064600f, -0.13179077f, 0.19937468f, -0.05775224f, 0.01649516f, 0.10100983f, 0.02097911f, 0.03833544f, 0.03181635f, -0.02967372f, -0.00601296f, 0.09454828f, -0.07086121f, -0.02754128f, -0.07009848f, 0.04036295f, -0.02212281f, -0.12408759f, -0.03062819f, -0.10545297f, 0.15279725f, 0.23442674f, -0.03790233f, -0.01476305f, -0.08318648f, 0.12385163f, -0.18972942f, 0.08998052f, 0.04918348f, 0.13086933f, -0.22088194f, -0.09628344f, 0.04302313f, -0.24255589f, -0.45634222f, 0.14161664f, -0.13278842f, 0.13931236f, 0.03457410f, -0.14659359f, -0.07559959f, -0.04807262f, 0.10688534f, -0.03848106f, -0.03899021f, 0.02318343f, 0.09349942f, 0.06242722f, -0.05112671f, -0.06820969f, 0.05657011f, 0.08681424f, -0.00924931f, -0.08001355f, -0.32376078f, -0.19641736f, -0.01402410f, -0.14274880f, -0.38780269f, 0.09231328f, -0.14018352f, -0.03672060f, -0.00284143f, 0.02102125f, -0.00396330f };
    }

    template<typename TPrecisionTag>
    class GatedDeltaRuleCudaTests : public ::testing::Test
    {
    protected:
        static constexpr TensorDataType P = TPrecisionTag::value;

        using RuleType = Mila::Dnn::GatedDeltaRule<DeviceType::Cuda, P>;
        using DeviceTensor = Tensor<P, CudaDeviceMemoryResource>;
        using HostFp32 = Tensor<TensorDataType::FP32, CpuMemoryResource>;

        void SetUp() override
        {
            try
            {
                cuda_context_ = createExecutionContext( Device::Cuda( 0 ) );
            }
            catch ( const std::exception& )
            {
                cuda_context_ = nullptr;
            }

            if ( !cuda_context_ )
            {
                GTEST_SKIP() << "CUDA device not available";
            }
        }

        static GatedDeltaRuleConfig config()
        {
            return GatedDeltaRuleConfig( kKeyHeads, kValueHeads, kHeadKeyDim, kHeadValueDim );
        }

        std::unique_ptr<RuleType> builtRule( dim_t steps )
        {
            auto rule = std::make_unique<RuleType>( "delta_rule", config(), Device::Cuda( 0 ) );
            rule->build( BuildContext( shape_t{ kBatch, steps, kValueWidth }, RuntimeMode::Inference, false ) );

            auto parameters = rule->getParameters();
            copy( hostFrom( kALog, shape_t{ kValueHeads } ),
                *static_cast<DeviceTensor*>( parameters[ 0 ] ), cuda_context_.get() );
            copy( hostFrom( kDtBias, shape_t{ kValueHeads } ),
                *static_cast<DeviceTensor*>( parameters[ 1 ] ), cuda_context_.get() );
            cuda_context_->synchronize();

            return rule;
        }

        HostFp32 hostFrom( const float* source, const shape_t& shape )
        {
            HostFp32 host( Device::Cpu(), shape );

            for ( dim_t i = 0; i < host.size(); ++i )
            {
                host.data()[ i ] = source[ i ];
            }

            return host;
        }

        /// A [kBatch, count, width] slice of a whole-sequence array, starting at `start`.
        HostFp32 hostSlice( const float* source, dim_t width, dim_t start, dim_t count )
        {
            HostFp32 host( Device::Cpu(), shape_t{ kBatch, count, width } );

            for ( dim_t t = 0; t < count; ++t )
            {
                for ( dim_t w = 0; w < width; ++w )
                {
                    host.data()[ t * width + w ] = source[ (start + t) * width + w ];
                }
            }

            return host;
        }

        DeviceTensor toDevice( const HostFp32& host )
        {
            DeviceTensor device( Device::Cuda( 0 ), host.shape() );
            copy( host, device, cuda_context_.get() );
            cuda_context_->synchronize();

            return device;
        }

        HostFp32 toFloat( const DeviceTensor& device )
        {
            auto host = toHost<TensorDataType::FP32>( device, cuda_context_.get() );
            cuda_context_->synchronize();

            return host;
        }

        std::unique_ptr<IExecutionContext> cuda_context_;
    };

    TYPED_TEST_SUITE( GatedDeltaRuleCudaTests, DeltaRulePrecisions, PrecisionNames );

    // ====================================================================
    // A. Construction and geometry
    // ====================================================================

    TYPED_TEST( GatedDeltaRuleCudaTests, Construct_StandaloneSucceeds )
    {
        typename TestFixture::RuleType rule( "delta_rule", TestFixture::config(), Device::Cuda( 0 ) );

        EXPECT_EQ( rule.getDeviceId().type, DeviceType::Cuda );
        EXPECT_EQ( rule.getType(), ComponentType::GatedDeltaRule );
    }

    TYPED_TEST( GatedDeltaRuleCudaTests, ParametersAreALogAndDtBias )
    {
        auto rule = this->builtRule( kSteps );

        EXPECT_EQ( rule->getParameterNames().size(), 2u );
        EXPECT_EQ( rule->parameterCount(), 2 * kValueHeads );
    }

    TYPED_TEST( GatedDeltaRuleCudaTests, RejectsValueHeadsThatDoNotGroupOverKeyHeads )
    {
        EXPECT_THROW( (void)GatedDeltaRuleConfig( 4, 6, 4, 4 ), std::invalid_argument );
    }

    TYPED_TEST( GatedDeltaRuleCudaTests, RejectsAHeadKeyDimTheKernelCannotHoldInRegisters )
    {
        EXPECT_THROW( (void)GatedDeltaRuleConfig( 2, 6, 256, 4 ), std::invalid_argument );
    }

    // ====================================================================
    // B. Against the validated oracle
    // ====================================================================

    TYPED_TEST( GatedDeltaRuleCudaTests, WholeSequence_MatchesTheReferenceOracle )
    {
        auto rule = this->builtRule( kSteps );

        auto q = this->toDevice( this->hostSlice( kQ, kKeyWidth, 0, kSteps ) );
        auto k = this->toDevice( this->hostSlice( kK, kKeyWidth, 0, kSteps ) );
        auto v = this->toDevice( this->hostSlice( kV, kValueWidth, 0, kSteps ) );
        auto a = this->toDevice( this->hostSlice( kA, kValueHeads, 0, kSteps ) );
        auto b = this->toDevice( this->hostSlice( kB, kValueHeads, 0, kSteps ) );

        auto& device_out = rule->prefill( q, k, v, a, b, 0 );
        rule->synchronize();

        auto out = this->toFloat( device_out );

        for ( dim_t i = 0; i < kSteps * kValueWidth; ++i )
        {
            EXPECT_NEAR( out.data()[ i ], kExpectedOut[ i ], TypeParam::atol ) << "at index " << i;
        }
    }

    // ====================================================================
    // C. The state equivalences
    // ====================================================================

    TYPED_TEST( GatedDeltaRuleCudaTests, SplitPrefillEqualsWholeSequence )
    {
        constexpr dim_t kFirst = 2;
        constexpr dim_t kSecond = kSteps - kFirst;

        auto rule = this->builtRule( kSteps );

        auto q1 = this->toDevice( this->hostSlice( kQ, kKeyWidth, 0, kFirst ) );
        auto k1 = this->toDevice( this->hostSlice( kK, kKeyWidth, 0, kFirst ) );
        auto v1 = this->toDevice( this->hostSlice( kV, kValueWidth, 0, kFirst ) );
        auto a1 = this->toDevice( this->hostSlice( kA, kValueHeads, 0, kFirst ) );
        auto b1 = this->toDevice( this->hostSlice( kB, kValueHeads, 0, kFirst ) );

        auto& first_device = rule->prefill( q1, k1, v1, a1, b1, 0 );
        rule->synchronize();
        auto first = this->toFloat( first_device );

        for ( dim_t i = 0; i < kFirst * kValueWidth; ++i )
        {
            EXPECT_NEAR( first.data()[ i ], kExpectedOut[ i ], TypeParam::atol )
                << "first chunk, index " << i;
        }

        auto q2 = this->toDevice( this->hostSlice( kQ, kKeyWidth, kFirst, kSecond ) );
        auto k2 = this->toDevice( this->hostSlice( kK, kKeyWidth, kFirst, kSecond ) );
        auto v2 = this->toDevice( this->hostSlice( kV, kValueWidth, kFirst, kSecond ) );
        auto a2 = this->toDevice( this->hostSlice( kA, kValueHeads, kFirst, kSecond ) );
        auto b2 = this->toDevice( this->hostSlice( kB, kValueHeads, kFirst, kSecond ) );

        auto& second_device = rule->prefill( q2, k2, v2, a2, b2, kFirst );
        rule->synchronize();
        auto second = this->toFloat( second_device );

        for ( dim_t i = 0; i < kSecond * kValueWidth; ++i )
        {
            EXPECT_NEAR( second.data()[ i ], kExpectedOut[ kFirst * kValueWidth + i ],
                TypeParam::atol ) << "second chunk, index " << i;
        }
    }

    TYPED_TEST( GatedDeltaRuleCudaTests, TokenByTokenDecodeEqualsWholeSequence )
    {
        auto rule = this->builtRule( 1 );

        for ( dim_t t = 0; t < kSteps; ++t )
        {
            auto q = this->toDevice( this->hostSlice( kQ, kKeyWidth, t, 1 ) );
            auto k = this->toDevice( this->hostSlice( kK, kKeyWidth, t, 1 ) );
            auto v = this->toDevice( this->hostSlice( kV, kValueWidth, t, 1 ) );
            auto a = this->toDevice( this->hostSlice( kA, kValueHeads, t, 1 ) );
            auto b = this->toDevice( this->hostSlice( kB, kValueHeads, t, 1 ) );

            auto& step_device = (t == 0)
                ? rule->prefill( q, k, v, a, b, 0 )
                : rule->decode( q, k, v, a, b, t );

            rule->synchronize();
            auto step = this->toFloat( step_device );

            for ( dim_t w = 0; w < kValueWidth; ++w )
            {
                EXPECT_NEAR( step.data()[ w ], kExpectedOut[ t * kValueWidth + w ],
                    TypeParam::atol ) << "step " << t << " width " << w;
            }
        }
    }

    /**
     * @brief Positive control for the two equivalences above.
     *
     * They would also pass against a rule that carried no state at all if the inputs
     * happened not to depend on history. Running the tail as a FRESH sequence must diverge
     * from the whole-sequence answer -- if it ever stops diverging, the equivalences have
     * stopped distinguishing a carried state from a discarded one.
     */
    TYPED_TEST( GatedDeltaRuleCudaTests, DiscardingTheStateChangesTheContinuation )
    {
        constexpr dim_t kFirst = 2;
        constexpr dim_t kSecond = kSteps - kFirst;

        auto rule = this->builtRule( kSecond );

        auto q2 = this->toDevice( this->hostSlice( kQ, kKeyWidth, kFirst, kSecond ) );
        auto k2 = this->toDevice( this->hostSlice( kK, kKeyWidth, kFirst, kSecond ) );
        auto v2 = this->toDevice( this->hostSlice( kV, kValueWidth, kFirst, kSecond ) );
        auto a2 = this->toDevice( this->hostSlice( kA, kValueHeads, kFirst, kSecond ) );
        auto b2 = this->toDevice( this->hostSlice( kB, kValueHeads, kFirst, kSecond ) );

        // position_offset 0 means "this is the start", which zeroes the state.
        auto& fresh_device = rule->prefill( q2, k2, v2, a2, b2, 0 );
        rule->synchronize();
        auto fresh = this->toFloat( fresh_device );

        float max_divergence = 0.0f;

        for ( dim_t i = 0; i < kSecond * kValueWidth; ++i )
        {
            max_divergence = std::max( max_divergence,
                std::fabs( fresh.data()[ i ] - kExpectedOut[ kFirst * kValueWidth + i ] ) );
        }

        // ABSOLUTE, not a multiple of atol. How far the two answers separate is a property
        // of these inputs (measured 0.2197, the same in both precisions), not of the
        // storage type -- scaling the bar by a per-precision tolerance moves the bar above
        // the signal in the looser arm and the control fails for the wrong reason. 0.05
        // clears BF16's 2e-2 noise floor and sits well under the real divergence.
        EXPECT_GT( max_divergence, 0.05f )
            << "discarding the recurrent state changed nothing -- the equivalence tests "
               "above cannot be distinguishing a carried state from a discarded one";
    }

    // ====================================================================
    // D. Guard clauses
    // ====================================================================

    TYPED_TEST( GatedDeltaRuleCudaTests, ForwardBeforeBuildIsRefused )
    {
        typename TestFixture::RuleType rule( "delta_rule", TestFixture::config(), Device::Cuda( 0 ) );

        auto q = this->toDevice( this->hostSlice( kQ, kKeyWidth, 0, 1 ) );
        auto k = this->toDevice( this->hostSlice( kK, kKeyWidth, 0, 1 ) );
        auto v = this->toDevice( this->hostSlice( kV, kValueWidth, 0, 1 ) );
        auto a = this->toDevice( this->hostSlice( kA, kValueHeads, 0, 1 ) );
        auto b = this->toDevice( this->hostSlice( kB, kValueHeads, 0, 1 ) );

        EXPECT_THROW( (void)rule.forward( q, k, v, a, b ), std::runtime_error );
    }
}
