name: Build Mila Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  documentation:
    uses: ./github/workflows/setup.yml

  generate-docs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Configure CMake
        run: |
          # Set environment variables for C++ modules scanning
          export CMAKE_CXX_SCAN_FOR_MODULES=AUTO  
          cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CUDA_COMPILER=$CUDA_PATH/bin/nvcc \
              -DCMAKE_CUDA_FLAGS="--allow-unsupported-compiler" \
              -DCMAKE_CXX_SCAN_FOR_MODULES=AUTO
      - name: Generate Documentation
        run: cmake --build ${{github.workspace}}/build --target docs
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{github.workspace}}/docs
          branch: gh-pages