name: Common Setup

on:
  workflow_call:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GCC 14
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 140
          sudo update-alternatives --set gcc /usr/bin/gcc-14
          sudo update-alternatives --set g++ /usr/bin/g++-14
          gcc --version
          g++ --version
      - name: Install CMake 3.31.7
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.7/cmake-3.31.7-linux-x86_64.tar.gz
          tar -xzf cmake-3.31.7-linux-x86_64.tar.gz
          sudo cp -r cmake-3.31.7-linux-x86_64/bin/* /usr/local/bin/
          sudo cp -r cmake-3.31.7-linux-x86_64/share/* /usr/local/share/
          cmake --version
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz build-essential ninja-build
          sudo apt-get install -y libgtest-dev
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: '12.8.1'
          method: 'network'
      - name: Verify CUDA installation
        run: |
          nvcc --version
          echo "CUDA_PATH: $CUDA_PATH"
          ls -la $CUDA_PATH/bin
          ls -la $CUDA_PATH/lib64 || echo "lib64 not found"
          ls -la $CUDA_PATH/lib || echo "lib not found"
      - name: Install miniz dependency
        run: |
          git clone https://github.com/richgel999/miniz.git
          cd miniz
          cmake -B build -G Ninja
          cmake --build build --config Release
          sudo cmake --install build