name: Test Mila Library

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    uses: ./.github/workflows/setup.yml@master

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CUDA_COMPILER=$CUDA_PATH/bin/nvcc \
              -DCMAKE_CUDA_FLAGS="--allow-unsupported-compiler"
      - name: Build Project
        run: cmake --build build --config Release
      - name: Run Tests
        working-directory: build
        run: ctest -C Release